RouletteExplorer/Controllers/ReportsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RouletteExplorer.Interfaces.Managers.Report;
using RouletteExplorer.ViewModels;

namespace RouletteExplorer.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportManager _reportManager;
        private readonly Guid? _wheelId;


        public ReportsController(IReportManager reportManager, RouletteExplorerContext context)
        {
            _reportManager = reportManager;
            _wheelId = context.Wheels.SingleOrDefault(x => x.IsActive)?.Id;
        }

        public IActionResult InsideBetReport()
        {

            var viewModel = new InsideBetReportViewModel
            {
                InsideBetReportName = "Inside Bet Report",
                InsideBetReport = _reportManager.GetInsideBetReport(_wheelId)
            };

            return View(viewModel);
        }

        public IActionResult OutsideBetReport()
        {

            var viewModel = new OutsideBetReportViewModel
            {
                OutsideBetReportName = "Outside Bet Report",
                OutsideBetReport = _reportManager.GetOutsideBetReport(_wheelId),
            };

            return View(viewModel);
        }

        public IActionResult StreakReport()
        {

            var viewModel = new StreakReportViewModel
            {
                StreakReportName = "Streak Report",
                StreakReport = _reportManager.GetStreakReport(_wheelId)
            };

            return View(viewModel);
        }

    }
}

RouletteExplorer/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using RouletteExplorer.ViewModels;
using ServiceStack;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RouletteExplorer.Controllers
{
    public class SettingsController : Controller
    {
        private readonly RouletteExplorerContext _context;
        private const string WheelId = "A7CCABF3-441B-4637-8180-BB5D7818EC82";

        public SettingsController(RouletteExplorerContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            var viewModel = new SettingsViewModel
            {
                Title = "Tracked Wheels",
                Wheels = _context.Wheels
                    .Where(x => !x.IsDeleted)
                    .Select(x => new Wheel
                    {
                        Id = x.Id,
                        Name = x.Name,
                        IsActive = x.IsActive,
                        Created = x.Created,
                        Spins = _context.Spin.Where(y => y.WheelId.Equals(x.Id)).ToList()
                    })
                    .OrderByDescending(w => w.IsActive).ThenByDescending(z => z.Created).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Wheel wheel)
        {
            if (ModelState.IsValid)
            {
                var newWheel = new Wheel()
                {
                    Id = Guid.NewGuid(),
                    Name = wheel.Name,
                    Created = DateTime.Now
                };
                _context.Add(newWheel);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View("Index");
        }


        public async Task<IActionResult> Delete([Bind("Id")] Guid id)
        {
            try
            {
                var wheel = _context.Wheels.SingleOrDefault(x => x.Id.Equals(id));

                if (wheel != null)
                {
                    wheel.IsActive = false;
                    wheel.IsDeleted = true;

                    _context.Update(wheel);

                    await _context.SaveChangesAsync();
                }
            }
            catch 
            {
                // suppress
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Activate([Bind("Id")] Guid id)
        {
            try
            {
                await using RouletteExplorerContext db = _context;

                List<Wheel> wheels = db.Wheels.ToList();

                wheels.ForEach(a => a.IsActive = false);

                Wheel wheel = _context.Wheels.SingleOrDefault(x => x.Id.Equals(id));

                if (wheel != null)
                {
                    wheel.IsActive = true;
                    db.Update(wheel);
                }

                await db.SaveChangesAsync();
            }
            catch
            {
                // suppress
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult AddWheel()
        {

            return View("Index");
        }

    }
}

RouletteExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]RouletteExplorer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark">
            <div class="container">
                <a class="navbar-brand font-weight-bolder" asp-area="" asp-controller="Home" asp-action="Index">RouletteExplorer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reports" asp-action="InsideBetReport">INSIDE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reports" asp-action="OutsideBetReport">OUTSIDE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reports" asp-action="StreakReport">STREAK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Settings" asp-action="Index">WHEELS/SETTINGS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>